from __future__ import annotations

import asyncio
import json
import logging
import re
import time
import urllib.error
import urllib.request
from typing import Any

from lumibot.config import NarrativeCfg
from lumibot.models import TokenCandidate

logger = logging.getLogger(__name__)

NARRATIVE_MAX_LEN = 100
_NARRATIVE_NA = {"N/A", "NA", "无", "未知", ""}

# Short-label link registry: (link-key, label, kind) — extracted from token_info,
# never generated by the LLM. Labels keep the 🔗 line to a single row.
_TWITTER_RE = re.compile(r"[A-Za-z0-9_]{1,15}")

# Domain-like tokens inside the LLM sentence get auto-linked by Telegram clients
# (e.g. "Pump.fun"). Insert a zero-width space after the dot to keep them plain.
_DEAUTOLINK_RE = re.compile(
    r"(?<![A-Za-z0-9])[A-Za-z0-9-]+\.(?:com|net|org|io|ai|fun|xyz|app|dev|me|co|cc|gg|link|so|pro|club|top|site|online|live|ru|cn|info|biz|tech|space|shop|store|games|network)(?![A-Za-z0-9])",
    re.IGNORECASE,
)


def deautolink(text: str) -> str:
    """Break Telegram's client-side auto-linking of domain-like tokens."""
    return _DEAUTOLINK_RE.sub(lambda m: m.group(0).replace(".", ".\u200b", 1), text)


_TRUNCATE_BOUNDS = "。；，、,.!?！？;"


def truncate_sentence(text: str, limit: int) -> str:
    """Cut at the last punctuation boundary within limit; append … when cut."""
    text = text.strip()
    if len(text) <= limit:
        return text
    cut = text[:limit]
    idx = max(cut.rfind(c) for c in _TRUNCATE_BOUNDS)
    if idx > limit * 0.5:
        cut = cut[: idx + 1]
    return cut.rstrip() + "…"


def _safe_url(value: object) -> str | None:
    """http(s) URL free of HTML-attribute breaking characters."""
    if value is None:
        return None
    u = str(value).strip()
    if not u.startswith(("http://", "https://")):
        return None
    if any(ch in u for ch in ('"', "<", ">", "'", " ")):
        return None
    return u


def extract_social_links(info: dict | None) -> list[str]:
    """Rendered 🔗 line items: short-label hyperlinks, deduped, first per type.

    X is built from the validated username; other links use the raw http(s) URL.
    A CTO token (dev.cto_flag) labels its telegram link 社区 instead of TG.
    """
    if not isinstance(info, dict):
        return []
    link = info.get("link")
    if not isinstance(link, dict):
        return []
    dev = info.get("dev")
    cto = bool(
        isinstance(dev, dict)
        and str(dev.get("cto_flag") or "").strip().lower() in ("1", "true", "yes")
    )
    out: list[str] = []
    seen: set[str] = set()

    def add(label: str, url: str | None) -> None:
        if label in seen:
            return
        seen.add(label)
        if url:
            out.append(f'<a href="{url}">{label}</a>')

    tw = str(link.get("twitter_username") or "").strip()
    if _TWITTER_RE.fullmatch(tw):
        add("X", f"https://x.com/{tw}")
    add("官网", _safe_url(link.get("website")))
    tg = _safe_url(link.get("telegram"))
    if tg:
        add("社区" if cto else "TG", tg)
    add("DC", _safe_url(link.get("discord")))
    add("YT", _safe_url(link.get("youtube")))
    add("IG", _safe_url(link.get("instagram")))
    add("TT", _safe_url(link.get("tiktok")))
    return out


class NarrativeClient:
    """Minimal OpenAI-compatible chat client for narrative inference (stdlib urllib)."""

    def __init__(self, api_key: str, cfg: NarrativeCfg) -> None:
        self.api_key = api_key
        self.cfg = cfg
        self.base_url = cfg.base_url.rstrip("/")

    async def complete(self, *, system: str, user: str) -> dict[str, Any]:
        payload = {
            "model": self.cfg.model,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            "temperature": 0,
            "max_tokens": 128,
            "response_format": {"type": "json_object"},
        }
        body = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            f"{self.base_url}/chat/completions",
            data=body,
            method="POST",
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
                "Accept": "application/json",
                "User-Agent": "lumibot-narrative/0.1",
            },
        )

        def _sync() -> Any:
            with urllib.request.urlopen(req, timeout=self.cfg.timeout_sec) as resp:
                raw = resp.read().decode("utf-8", errors="replace")
                return json.loads(raw) if raw else {}

        return await asyncio.to_thread(_sync)


class NarrativeCache:
    """TTL cache of resolved narratives, keyed by (chain, address)."""

    def __init__(self, ttl_sec: int) -> None:
        self.ttl = ttl_sec
        self._store: dict[tuple[str, str], tuple[float, str]] = {}

    def get(self, chain: str, address: str) -> str | None:
        key = (chain, address)
        item = self._store.get(key)
        if not item:
            return None
        ts, value = item
        if time.time() - ts > self.ttl:
            self._store.pop(key, None)
            return None
        return value

    def set(self, chain: str, address: str, value: str) -> None:
        if not value:
            return
        self._store[(chain, address)] = (time.time(), value)

    def clear(self) -> None:
        self._store.clear()


SYSTEM_PROMPT = (
    "你是加密 meme 币叙事分析师。根据给定代币信息，"
    f"用不超过 {NARRATIVE_MAX_LEN} 个汉字写一段信息量丰富的叙事描述，"
    "覆盖以下维度（信息不足的维度省略）："
    "1) 主题/概念（如特朗普概念、AI Agent、动物 meme）；"
    "2) 定位/来源（官方项目/社区接管/仿盘、发行平台）；"
    "3) 社区热度信号（简介提及的社区动态）；"
    "4) 风险线索（新地址、持仓集中、税、开发者行为）；"
    "5) 开发者背景（历史发币数量）；"
    "6) 聪明钱/老鼠仓信号（只能引用给定数值，不得编造数字或链接）。"
    '信息严重不足时输出 "N/A"。只输出 JSON: {"narrative": "..."}'
)


class NarrativeService:
    """LLM narrative inference with cache and guardrails. Pure display, no gating."""

    def __init__(self, api_key: str, cfg: NarrativeCfg) -> None:
        self.cfg = cfg
        self.client = NarrativeClient(api_key, cfg)
        self.cache = NarrativeCache(cfg.cache_ttl_sec)
        self._blocked = {s.lower() for s in cfg.symbol_blocklist}

    async def narrative_for(self, cand: TokenCandidate, info: dict[str, Any]) -> str | None:
        """Return a narrative sentence (<=30 chars) or None when unavailable."""
        if not self._eligible(cand):
            logger.info(
                "narrative_skipped chain=%s token=%s symbol=%r (ineligible)",
                cand.chain,
                cand.address,
                cand.symbol,
            )
            return None
        cached = self.cache.get(cand.chain, cand.address)
        if cached is not None:
            return cached
        try:
            text = await self._infer(cand, info)
        except Exception as exc:  # noqa: BLE001
            logger.warning(
                "narrative_infer_failed chain=%s token=%s err=%s",
                cand.chain,
                cand.address,
                exc,
            )
            return None
        if text is None:
            logger.info(
                "narrative_na chain=%s token=%s symbol=%r (LLM N/A)",
                cand.chain,
                cand.address,
                cand.symbol,
            )
            return None
        self.cache.set(cand.chain, cand.address, text)
        return text

    def _eligible(self, cand: TokenCandidate) -> bool:
        sym = (cand.symbol or "").strip()
        if len(sym) < self.cfg.min_symbol_len:
            return False
        if sym.lower() in self._blocked:
            return False
        return True

    async def _infer(self, cand: TokenCandidate, info: dict[str, Any]) -> str | None:
        link = info.get("link") if isinstance(info.get("link"), dict) else {}
        desc = str(link.get("description") or "").strip()[:200]
        website = str(link.get("website") or "").strip()[:100]
        name = (cand.name or "").strip()
        stat = info.get("stat") if isinstance(info.get("stat"), dict) else {}
        wts = info.get("wallet_tags_stat") if isinstance(info.get("wallet_tags_stat"), dict) else {}
        platform = str(info.get("launchpad_platform") or info.get("launchpad") or "").strip()[:30]
        # Missing dimensions are omitted from the prompt (never injected as None).
        parts = [f"symbol={cand.symbol}"]
        if name:
            parts.append(f"name={name}")
        if desc:
            parts.append(f"desc={desc}")
        if website:
            parts.append(f"website={website}")
        if platform:
            parts.append(f"platform={platform}")
        for key, val in (
            ("creator_open_count", stat.get("creator_created_count")),
            ("rat_ratio", stat.get("top_rat_trader_percentage")),
            ("bundler_ratio", stat.get("top_bundler_trader_percentage")),
            ("smart_wallets", wts.get("smart_wallets")),
        ):
            if val is not None:
                parts.append(f"{key}={val}")
        user = " ".join(parts)
        data = await self.client.complete(system=SYSTEM_PROMPT, user=user)
        narrative = self._extract(data)
        if narrative is None:
            return None
        return truncate_sentence(narrative, NARRATIVE_MAX_LEN)

    @staticmethod
    def _extract(data: Any) -> str | None:
        try:
            content = data["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError):
            return None
        if isinstance(content, str):
            text = content.strip()
        else:
            text = str(content).strip()
        if not text:
            return None
        try:
            parsed = json.loads(text)
            if isinstance(parsed, dict):
                text = str(parsed.get("narrative") or "").strip()
        except (TypeError, ValueError):
            pass
        text = text.strip().strip("\"'")
        if text in _NARRATIVE_NA:
            return None
        return text or None
